### ISSUE TITLE
Implement delegate system

### ISSUE THREAD

**Issue by TomForus** [teamforus/me#15]
- [ ] Demo @danrminds 
- [ ] iOS @jamalv
- [ ] Android @martijndoornik

**Comment by danrminds** [comment]
Is this relevant still?

**Comment by danrminds** [comment]
This feature is left out for MVP. Close temporarily? @jamalv

**Comment by danrminds** [comment]
Oh, it is in Longterm vision backlog. Can be left opened

**Comment by maxvisser** [comment]
I personally feel that long term issues should not be created. This issue feels like 'I want a better world for my children' without concrete steps to do it within a concrete timeframe.

**Comment by jamalv** [comment]
- [ ] 1. make love, not war [couple decades at least]
- [ ] 2. transition to an abundance economy [also a couple decades]
- [ ] 3. make some children [9 months at least]

In the meantime, this issue was superseded by: https://github.com/teamforus/research-and-development/issues/97 :)

_side note:_ I don't mind long term issues, maybe as reminders, but think the labels should clarify that

**Comment by martijndoornik** [comment]
On that side note: perhaps have a "Vision" label? Or "Roadmap"?
