### ISSUE TITLE
Let user skip creating password on creation Me identity, dont use it when doing transaction

### ISSUE THREAD

**Issue by GerbenBosschieter** [teamforus/me#224]
**Is your feature request related to a problem? Please describe.**
We are using a passcode in the Me-app. The passcode is currently being used to open the Me-app.
If you forget the passcode, you cant do anything to get in the app. You can not even switch or reload your profile in to the app. Unless you delete the app and download again.

**Describe the solution you'd like**
After reviewing some other apps (also apps with personal information like IRMA and BUNQ) we came to the conclusion that all of these apps don't ask for the passcode until you want to do something that needs the user his permission.

Those apps are okay with opening the app and seeing the information, because they rely on the security of the device itself. I propose to to the same as the other apps.

- Ask to create a passcode while creating a profile or logging in.
- Only ask for the passcode if the users wants to confirm a payment (as a citizen), change the passcode or other features that may be added in the future and need the users his permission (like records)

On Android we asked to create a passcode after connecting it to your profile. On iOS we don't do this. It would be nice if we can align these two. In my opinion we should not force the user to create a passcode but give them the option. So I like it how we do it currently on iOS. And yes I know you can skip it, but it's not clear enough. Best alternative is to add a clear skip button. We already got calls from providers who forget that they created the passcode.

Sometimes these subjects are UX versus Security. And for now I think it's best to give the user the best UX. Cause we need to statisfy our current users for future implementations.

**Describe alternatives you've considered**
- Add a button for switching profile while entering the passcode (so there Is still a way to log in if they forget the passcode without reinstalling the app)
- Log out the profile after multiple wrong passcode attempts (also prevents reinstalling the app if you forget the code)

**Comment by danieltcacenco** [comment]
I am not almost agree with that, because to let password only for some action is not so good we have a voucher and profile of user witch can be personal he don't want to look someone in other bank app for example for first time enter it ask for passcode its something normal and in our case when we have voucher in other voucher may be some personal information.

**Comment by jknnr** [comment]
iOS done

**Comment by GerbenBosschieter** [comment]
What is exactly done. As I understand now the passcode is asked when a transaction needs to be confirmed. What did you guys with the other points

**Comment by maxvisser** [comment]
I would suggest to enter pincode only after 3 days. Fill in pincode on launch, set date in local storage. if time > 3 days later; ask passcode again.

**Comment by maxvisser** [comment]
https://github.com/teamforus/me/issues/240

**Comment by jknnr** [comment]
Current consensus is that we added the passcode on transaction confirmation. And it also stays on the entrance. 
Later we could make a dedicated menu "privacy and security" where you can decide, if you want to leave the entrance password or not.
Will remind you that the argument for having the passcode on entrance is the privacy demand concerning the vouchers, data on which is already a private information.
But the main issue is what happens when one forgot the password. For now you have to reinstall the app, which is not so critical (imo).
At the moment we are implementing the button "log out" on the passcode screen. It will log the user out and erase the passcode. 
So if the user is at the shop and he forgot the code, he can just log out, log in with e-mail and finish the transaction.
The functionality will be done today, so we will test the UX soon.

**Comment by maxvisser** [comment]
Just discussed the current implementation with passcode on transaction, we mimicked the interaction and we think it can be confusing for the end user that we ask the passcode on transaction. As in a normal transaction the one who is paying has to filled in the passcode.

I think we should remove it for now until we implement the whole interaction

**Comment by GerbenBosschieter** [comment]
@maxvisser I agree. It's weird for the provider to enter a passcode for receiving money. Only if you are spending money it's logic to do so.

**Comment by GerbenBosschieter** [comment]
@jknnr On Android we asked to create a passcode after connecting it to your profile. On iOS we don't do this. It would be nice if we can align these two. In my opinion we should not force the user to create a passcode but give them the option. So I like it how we do it currently on iOS. And yes I know you can skip it, but it's not clear enough. Already got calls from providers who forget that they created the passcode.

And also want to say something about this argument:
Will remind you that the argument for having the passcode on entrance is the privacy demand concerning the vouchers, data on which is already a private information.

I agree with it partially. I have a-lot of apps with my personal information that don't ask to enter a passcode. Even my app of the government and my bank app don't ask for it.
Everybody has a passcode, fingerprint or face id on their phone to acces it.

Sometimes these subjects are UX versus Security. And for now I think it's best to give the user the best UX. Caus we need to statisfy our current users for future implementations.

**Comment by maxvisser** [comment]
lets check if android does the same with passcode as iOS

**Comment by maxvisser** [comment]
done
