### ISSUE TITLE
When used voucher are added back, label them as used.

### ISSUE THREAD

**Issue by maxvisser** [teamforus/me#280]
## Context/goal: 
When we add used and expired vouchers back to the list we should label them

Example of webshop:
![image](https://user-images.githubusercontent.com/10818702/54309342-39fe6c00-45d0-11e9-8f2c-26986ab30584.png)

Label used NL 'Gebruikt' should be yellow.
Label expired NL 'Verlopen' should be red.

When used and expired we should always 'used' 

If vouchers is active and not used/expired. we don't show any labels.

**Comment by maxvisser** [comment]
remove labels in app for now

until we implement a feature like https://github.com/teamforus/me/issues/276 we don't need labels

**Comment by GerbenBosschieter** [comment]
This is still the same, the used vouchers are hidden. We would like to keep it this way for now right ? I think with the current overload of information we get from the API it safer to hide them than show them with labels. The app is will become really slow if we have a lot of vouchers.

@maxvisser 
I am not sure if I can close this issue, because you referenced #276
