### ISSUE TITLE
Kies organisatie is double

### ISSUE THREAD

**Issue by maxvisser** [teamforus/me#294]
## Context/goal: 
Choose organisation is only needed once above list

![TenLYTIM](https://user-images.githubusercontent.com/10818702/60339160-4b655b80-99a8-11e9-8682-de7c3bb311e7.jpeg)

**Comment by maxvisser** [comment]
![](https://chat.forus.io/file-upload/qa2PYnkhRx9CKWph9/TenLYTIM.jpeg)

**Comment by maxvisser** [comment]
Hi daniel, this issue is about label 'Kies organisatie' being double. I see you fixed that it now shows the chosen organization.

**Comment by GerbenBosschieter** [comment]
I can see that this is still the same. This is definitely not a reason to stop this release. But the issue itself is not fixed yet. Or I don't understand what exactly the meaning of this issue is

![image](https://user-images.githubusercontent.com/38419514/60950081-c73f9c00-a2f6-11e9-874d-90c0bef99be2.png)

**Comment by maxvisser** [comment]
Yes you have the meaning of this issue just right;) seems not fixed yet

**Comment by maxvisser** [comment]
done
