### ISSUE TITLE
Onboarding screens

### ISSUE THREAD

**Issue by jknnr** [teamforus/me#443]
The task is to create simple instructions for the new user when he opens the app.

- [x] - Discuss with @Myshelova and make a few concepts with reference.
- [x] - Refine with the team
- [x] - Make designs ios
- [x] - Make designs android
- [ ] - Implement ios
- [ ] - Implement android

Here you can find links to prototypes in Figma:
iOS Light Mode: https://www.figma.com/file/Dyk8ACF91stjmWmO3rUpXv/?node-id=1675%3A0
iOS Dark Mode: https://www.figma.com/file/Dyk8ACF91stjmWmO3rUpXv/?node-id=1565%3A0
Android: https://www.figma.com/file/zlpC5I10BP0M8sS5ueHor4/?node-id=1028%3A0

**Comment by Myshelova** [comment]
Some references for our onboarding screens

![image](https://user-images.githubusercontent.com/22478043/84260985-4b0f9300-ab1b-11ea-853d-9f7251525ad1.png)
![image](https://user-images.githubusercontent.com/22478043/84260999-519e0a80-ab1b-11ea-8194-1d53467c7d89.png)
![image](https://user-images.githubusercontent.com/22478043/84261003-5793eb80-ab1b-11ea-95ae-3a129ea91f7b.png)
![image](https://user-images.githubusercontent.com/22478043/84261014-5d89cc80-ab1b-11ea-82d1-01c97e4f3dcb.png)
![image](https://user-images.githubusercontent.com/22478043/84261020-61b5ea00-ab1b-11ea-94e3-3235776da764.png)
![image](https://user-images.githubusercontent.com/22478043/84261032-667a9e00-ab1b-11ea-9894-f5c9afab36f0.png)
![image](https://user-images.githubusercontent.com/22478043/84261043-6aa6bb80-ab1b-11ea-8903-ca05d99f1acd.png)
![image](https://user-images.githubusercontent.com/22478043/84261054-709c9c80-ab1b-11ea-80f2-d4fd6c064bbe.png)
![image](https://user-images.githubusercontent.com/22478043/84261084-78f4d780-ab1b-11ea-950e-c3c18368a817.png)
![image](https://user-images.githubusercontent.com/22478043/84261105-7e522200-ab1b-11ea-9473-0ea952f271c1.png)
![image](https://user-images.githubusercontent.com/22478043/84261113-84480300-ab1b-11ea-8265-c000f1bb9c8e.png)

**Comment by jknnr** [comment]
@maxvisser @jamalv we should discuss if we want to separate the provider view from a requester inside of an app, so it can be  described here on the onboarding

**Comment by jamalv** [comment]
For now; no, it will make the scope too big.

**Comment by jamalv** [comment]
Here's some initial ideas: https://www.figma.com/file/ARUlmFPD1ZHOu5LZEgAY6P/%F0%9F%94%B5Me-information?node-id=16%3A65

**Comment by Myshelova** [comment]
Here you can find links to prototypes in Figma:
iOS Light Mode: https://www.figma.com/file/Dyk8ACF91stjmWmO3rUpXv/?node-id=1675%3A0
iOS Dark Mode: https://www.figma.com/file/Dyk8ACF91stjmWmO3rUpXv/?node-id=1565%3A0
Android: https://www.figma.com/file/zlpC5I10BP0M8sS5ueHor4/?node-id=1028%3A0

**Comment by GerbenBosschieter** [comment]
@Myshelova I've did the dutch text of the on boarding screens. I would like to ask @linda-90 to check if these text are any good. I didn't add them in figma because there are some (solvable) problems I currently have with Figma and can't fix this right away.

Me-app Onboarding

——————————————————————————————— 
Screen one:

Title: Welcome to Me
Description: De Me-app is jouw digitale portemonnee en kassa.
Skip tutorial: Tutorial overslaan

Skip: Overslaan
Next step: Volgende stap

———————————————————————————————— 
Screen two:

Title: Jouw digitale portemonnee
Description: Heb je een voucher ontvangen vanuit Forus? Log dan in op Me om je voucher veilig mee te nemen, je saldo en transacties in te zien, en om de voucher eenvoudig te presenteren aan de aanbieder.

Skip: Overslaan
Next step: Volgende stap 
——————————————————————————————— 
Screen three:

Title: Betalingen met de Me-app
Description: Bied jij je diensten en/of producten aan via Forus? Dan kun je mede Me-app QR codes scannen om betalingen te ontvangen. Het is mogelijk om meerdere kassamedewerkers aan de zelfde organisatie toe te voegen.

Skip: Overslaan
Next step: Volgende stap

———————————————————————————————

Screen four:

Title: Betalingen met de Me-app
Description: Bied jij je diensten en/of producten aan via Forus? Dan kun je mede Me-app QR codes scannen om betalingen te ontvangen. Het is mogelijk om meerdere kassamedewerkers aan de zelfde organisatie toe te voegen.

Skip: Overslaan
Next step: Volgende stap

———————————————————————————————

Screen five:

Title: Persoonlijke eigenschappen
Description: Beheer jouw persoonlijke eigenschappen en deel deze met een beoordelaar om in aanmerking te komen voor een tegoed die je hebt aangevraagd.

Skip: Overslaan
Next step: Volgende stap

———————————————————————————————

Screen six:

Title: Inloggen zonder wachtwoord
Description: Met Me kun je gemakkelijk inloggen op Forus. Heb je een voucher ontvangen of ben je medewerker van een betrokken organisatie? Gebruik Me om de QR code op de website te scannen zodat je veilig kan inloggen.

Skip: Overslaan
Login: Aanmelden

**Comment by GerbenBosschieter** [comment]
@maxvisser kun jij ook even checken

**Comment by jamalv** [comment]
heb het even in figma geplakt - sommige dingen kwamen niet helemaal lekker uit dus heb enkele aanpassingen gedaan - maar ziet er al wel echt nice uit.

figma: https://www.figma.com/file/Dyk8ACF91stjmWmO3rUpXv/Me-iOS?node-id=1708%3A557

**Comment by maxvisser** [comment]
volgensmij is QR-code met een streepje in het nederlands. Voor de rest ziet het er oké uit. Misschien ook wat moeite stoppen in de engelse versie?

**Comment by Myshelova** [comment]
Guys. I had a conversation with Yasha and we decided don't ask users questions on tutorial screens and make the affirmative conditional sentences. Reason for it – we're training users and there are no functional options to answer. It's just information, not iteration survey flow where the user can answer a question and choose yes or not

**Comment by linda-90** [comment]
@jamalv I am assigned. What exactly do you expect from me?
