### ISSUE TITLE
Me - Do you want to login?

### ISSUE THREAD

**Issue by maxvisser** [teamforus/me#523]
## Context/goal: 
Prototypes iOS & Android: 
https://www.figma.com/file/3F5FyFLJF1rzgsVto5KU1D/?node-id=223%3A1083 

![image](https://user-images.githubusercontent.com/10818702/100594097-85533380-32f9-11eb-9c01-30d05ecc2f93.png)
![image](https://user-images.githubusercontent.com/10818702/100594139-94d27c80-32f9-11eb-9486-6f61d3bf038e.png)

## Task

User currently get a popup which ask user if he is sure that he wants login (popup modal). We want to implement a full screen message which explain a bit of the dangers of scanning QR-codes and logging in. User should be sure its something he wants to do.

Texts:
Title: Probeer je in te loggen op een apparaat?
Description: Scan alleen QR-codes vanaf je eigen apparaten. Gebruik nooit een code die een andere gebruiiker naar je heeft gestuurd.
Button: ja, ik wil inloggen
Subtext button: Annuleren

Title: Do you want to login on this device?
Description: Scan only QR-codes on devices you own or temporarily use. Never scan a code which was sent or shown by another person.
Button: yes, i want to login
Subtext button: no thanks

**Comment by maxvisser** [comment]
On android this is done

**Comment by GerbenBosschieter** [comment]
I would like to do a new proposal for the texts because it doesn't fit our use case. We ask the users not to scan Qr Codes they received from other persons. But thats like our core use case xD. So something more fitting about logging would be nice.

@maxvisser do you agree?

**Text proposal**
Title: Probeer je in te loggen op een apparaat?
Description: Door verder te gaan met inloggen geef je een ander apparaat toegang tot je account. Weet je zeker dat je verder wilt gaan?
Button: ja, ik wil inloggen
Subtext button: Annuleren

Title: Do you want to login on this device?
Description: Continuing will allow this device to acces you account. Are you sure you want to continue? 
Button: yes, I want to login
Subtext button: no thanks

**Comment by GerbenBosschieter** [comment]
Done for iOS

**Comment by maestrovsmaster** [comment]
![image](https://user-images.githubusercontent.com/23098862/115283344-e7e78780-a153-11eb-8bb8-231e8b1145ec.png)
