### ISSUE TITLE
applying for fund via Me using activation code in Me

### ISSUE THREAD

**Issue by GerbenBosschieter** [teamforus/me#55]
**Is your feature request related to a problem? Please describe.**
On the voucher screen now it states that the user don't have any vouchers when they generate a new identity.

**Describe the solution you'd like**
Replace this ' you dont have any voucher' with a input field where the user can fill in their activation code and there by activating their voucher.

**Describe alternatives you've considered**
Adding this field somewhere else in the me app, maybe it make more sense to do this on the profile page because the activation codes adds records.

**Comment by jamalv** [comment]
For now this is out of scope anyway, when we decide to pick this up we can think about it a bit more.

For now, agree with Max that the voucher screen might not be the best place since it has to do with records. So maybe even add it to the record tab, or even better, we represent the pre-validated records with a QR code, so that someone can simply scan the QR code to add the records. 

**Sidenote:** We should be mindful that prevalidated records are much less trustworthy then actual validated records. It is more of a "now you have the records, go gather some validations" and by the way, "this is enough to get (a) certain voucher(s)" than that this really is a solid endorsement.

**Comment by maxvisser** [comment]
For this issue to be implements we need a funds overview and apply for fund on webshop

- [ ] adding the activation while signup
- [ ] add it to the profile page -> explain in popup what user needs to do after activation

- user gets records:
unique number (BSN or Customer number of municipality)
multiplier (amount of childern or other metric)
right for fund_id (apply for fund)

apply with these records on webshop.

**Comment by jamalv** [comment]
I think this issue was superseded by: https://github.com/teamforus/me/issues/63
