### ISSUE TITLE
Setting up a Feedback/Support WhatsApp group

### ISSUE THREAD

**Issue by maartenfv** [teamforus/me#60]
People are starting to download the app's and testing with them. Examples are: Erwin, Helga, etc. In the near future more people will be downloading the app.

These people are very useful as testers but they need a low barrier to report on any issues they might have. The majority of them are not going to write GitHub issues.

In order to still receive their feedback we can set up a whatsapp-group. Allowing them to send feedback on, and screenshots of the problems they might encounter.

Additional is adding a section in the about part of the app informing people on how they can give feedback.

**Comment by GerbenBosschieter** [comment]
I totally agree and will setup this group. I assume that the people you mentioned downloaded from the App Store / Play store. It's not really representative for the mobile application. Because they will not be able to join a fund or really use the app. 

We will include them in a new test group when all those issues mentioned at our last meeting are solved. But the WhatsApp group itself is done.

**Comment by maxvisser** [comment]
Maarten also suggested todsy to look into the costs of whatsapp business for feedback
